### ISSUE TITLE
Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing. Pillar key "metalk8s:endpoints:prometheus:ip" is missing.

### ISSUE THREAD

**Issue by JavierAbrego** [scality/metalk8s#1700]
After facing quite a lot of issues in the process I was able to build the iso for metalk8s from the branch development/2.4. It makes me think that it hasn't been used recently, for example, the thrift repositories from apache have been moved to Github and is giving an error. I had to update the mod and sum files of the storage module.

Now I'm trying to run it in a CentOS Linux 7 (Core) in order to deploy a bootstrap server.

I prepared the machine as follows:
```
yum -y install yum-plugin-versionlock &&
mkdir -p /srv/scality/metalk8s-2.0.0-dev &&
mount metalk8s.iso /srv/scality/metalk8s-2.0.0-dev &&
mkdir /etc/metalk8s &&
echo "
apiVersion: metalk8s.scality.com/v1alpha2
kind: BootstrapConfiguration
networks:
  controlPlane: 91.121.0.0/16
  workloadPlane: 91.121.0.0/16
ca:
  minion: bootstrap.revolucionmusic.com
apiServer:
  host: 91.121.87.160
archives:
  - /root/metalk8s.iso
" > /etc/metalk8s/bootstrap.yaml &&
mkdir -p /etc/metalk8s/pki &&
ssh-keygen -t rsa -b 4096 -N '' -f /etc/metalk8s/pki/salt-bootstrap
```

Then run the bootstrap script
```
[root@bootstrap ~]# /srv/scality/metalk8s-2.0.0-dev/bootstrap.sh
> Pre-minion system tests... done [0s]
> Disabling Salt minion service... done [0s]
> Stopping Salt minion service... done [1s]
> Configuring local YUM repositories... done [0s]
> Installing Salt minion... done [0s]
> Installing genisoimage... done [1s]
> Configuring Salt minion to run in local mode... done [6s]
> Calculating Salt grains in local mode... done [3s]
> Deploying early-stage bootstrap node in local mode (this may take a while)... done [130s]
> Syncing Utility modules on Salt master... done [2s]
> Syncing Pillar modules on Salt master... done [2s]
> Syncing Runner modules on Salt master... done [2s]
> Syncing Execution modules on Salt master... done [2s]
> Accepting bootstrap minion key on Salt master... done [24s]
> Refreshing all modules and data on bootstrap minion... done [4s]
> Deploying bootstrap node (this may take a while)... fail [411s]

Failure while running step 'Deploying bootstrap node (this may take a while)'

Command: crictl exec -i bb854ec12bc05077c6273e5298947841dc1d6320a42549af5b36daade4d4f795 salt-run --state-output=mixed state.orchestrate metalk8s.orchestrate.bootstrap saltenv=metalk8s-2.4.0-dev pillar={   'bootstrap_id': 'bootstrap.revolucionmusic.com' }

Output:

<< BEGIN >>
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt[ERROR   ] Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.
Pillar key "metalk8s:endpoints:prometheus:ip" is missing.
Pillar key "metalk8s:endpoints:prometheus:ip" is missing.

[ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'bootstrap.revolucionmusic.com_master': {u'test_|-Check pillar for MetalK8s UI_|-Check pillar for MetalK8s UI_|-check_pillar': {u'comment': u'Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.\nPillar key "metalk8s:endpoints:prometheus:ip" is missing.\n', u'name': u'Check pillar for MetalK8s UI', u'start_time': '19:38:39.361156', u'result': False, u'duration': 1.913, u'__run_num__': 0, u'__sls__': u'metalk8s.addons.ui.precheck', u'changes': {}, u'__id__': u'Check pillar for MetalK8s UI'}}}, u'retcode': 1}}
[ERROR   ] Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.
Pillar key "metalk8s:endpoints:prometheus:ip" is missing.

[ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'bootstrap.revolucionmusic.com_master': {u'test_|-Check pillar for MetalK8s UI_|-Check pillar for MetalK8s UI_|-check_pillar': {u'comment': u'Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.\nPillar key "metalk8s:endpoints:prometheus:ip" is missing.\n', u'name': u'Check pillar for MetalK8s UI', u'start_time': '19:39:12.668874', u'result': False, u'duration': 2.062, u'__run_num__': 0, u'__sls__': u'metalk8s.addons.ui.precheck', u'changes': {}, u'__id__': u'Check pillar for MetalK8s UI'}}}, u'retcode': 1}}
[ERROR   ] Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.
Pillar key "metalk8s:endpoints:prometheus:ip" is missing.

[ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'bootstrap.revolucionmusic.com_master': {u'test_|-Check pillar for MetalK8s UI_|-Check pillar for MetalK8s UI_|-check_pillar': {u'comment': u'Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.\nPillar key "metalk8s:endpoints:prometheus:ip" is missing.\n', u'name': u'Check pillar for MetalK8s UI', u'start_time': '19:39:45.762350', u'result': False, u'duration': 1.889, u'__run_num__': 0, u'__sls__': u'metalk8s.addons.ui.precheck', u'changes': {}, u'__id__': u'Check pillar for MetalK8s UI'}}}, u'retcode': 1}}
[ERROR   ] Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.
Pillar key "metalk8s:endpoints:prometheus:ip" is missing.

[ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'bootstrap.revolucionmusic.com_master': {u'test_|-Check pillar for MetalK8s UI_|-Check pillar for MetalK8s UI_|-check_pillar': {u'comment': u'Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.\nPillar key "metalk8s:endpoints:prometheus:ip" is missing.\n', u'name': u'Check pillar for MetalK8s UI', u'start_time': '19:40:18.860699', u'result': False, u'duration': 1.894, u'__run_num__': 0, u'__sls__': u'metalk8s.addons.ui.precheck', u'changes': {}, u'__id__': u'Check pillar for MetalK8s UI'}}}, u'retcode': 1}}
[ERROR   ] Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.
Pillar key "metalk8s:endpoints:prometheus:ip" is missing.

[ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'bootstrap.revolucionmusic.com_master': {u'test_|-Check pillar for MetalK8s UI_|-Check pillar for MetalK8s UI_|-check_pillar': {u'comment': u'Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.\nPillar key "metalk8s:endpoints:prometheus:ip" is missing.\n', u'name': u'Check pillar for MetalK8s UI', u'start_time': '19:40:52.012834', u'result': False, u'duration': 1.877, u'__run_num__': 0, u'__sls__': u'metalk8s.addons.ui.precheck', u'changes': {}, u'__id__': u'Check pillar for MetalK8s UI'}}}, u'retcode': 1}}
[WARNING ] org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
bootstrap.revolucionmusic.com_master:
  Name: saltutil.sync_all - Function: salt.runner - Result: Changed Started: - 19:34:09.726952 Duration: 1285.091 ms
  Name: saltutil.sync_roster - Function: salt.runner - Result: Changed Started: - 19:34:11.012287 Duration: 664.167 ms
  Name: metalk8s_saltutil.sync_auth - Function: salt.runner - Result: Changed Started: - 19:34:11.676758 Duration: 607.639 ms
  Name: saltutil.sync_all - Function: salt.function - Result: Changed Started: - 19:34:12.284664 Duration: 1420.357 ms
  Name: Deploy CA role on bootstrap minion - Function: salt.state - Result: Changed Started: - 19:34:13.706187 Duration: 13956.048 ms
  Name: Bring bootstrap minion to highstate - Function: salt.state - Result: Changed Started: - 19:34:27.664625 Duration: 156676.048 ms
  Name: Generate etcd client certs for salt master - Function: salt.state - Result: Changed Started: - 19:37:04.341144 Duration: 9043.312 ms
  Name: https://91.121.87.160:6443/healthz - Function: http.wait_for_successful_query - Result: Clean Started: - 19:37:13.386097 Duration: 16.585 ms
  Name: state.orchestrate - Function: salt.runner - Result: Changed Started: - 19:37:13.403617 Duration: 5630.957 ms
  Name: saltutil.refresh_pillar - Function: salt.function - Result: Changed Started: - 19:37:19.036252 Duration: 402.281 ms
  Name: mine.update - Function: salt.function - Result: Changed Started: - 19:37:19.439681 Duration: 882.505 ms
  Name: state.orchestrate - Function: salt.runner - Result: Changed Started: - 19:37:20.322697 Duration: 75828.329 ms
----------
          ID: Precheck for MetalK8s UI
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Runner function 'state.orchestrate' failed."
              Attempt 2: Returned a result of "False", with the following comment: "Runner function 'state.orchestrate' failed."
              Attempt 3: Returned a result of "False", with the following comment: "Runner function 'state.orchestrate' failed."
              Attempt 4: Returned a result of "False", with the following comment: "Runner function 'state.orchestrate' failed."
              Runner function 'state.orchestrate' failed.
     Started: 19:38:36.152004
    Duration: 135655.728 ms
     Changes:
              ----------
              return:
                  ----------
                  data:
                      ----------
                      bootstrap.revolucionmusic.com_master:
                          ----------
                          test_|-Check pillar for MetalK8s UI_|-Check pillar for MetalK8s UI_|-check_pillar:
                              ----------
                              __id__:
                                  Check pillar for MetalK8s UI
                              __run_num__:
                                  0
                              __sls__:
                                  metalk8s.addons.ui.precheck
                              changes:
                                  ----------
                              comment:
                                  Pillar key "metalk8s:endpoints:prometheus:ports:web:node_port" is missing.
                                  Pillar key "metalk8s:endpoints:prometheus:ip" is missing.
                              duration:
                                  1.877
                              name:
                                  Check pillar for MetalK8s UI
                              result:
                                  False
                              start_time:
                                  19:40:52.012834
                  outputter:
                      highstate
                  retcode:
                      1
----------
          ID: Deploy MetalK8s UI
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Precheck for MetalK8s UI
     Started: 19:40:52.021627
    Duration: 0.017 ms
     Changes:
  Name: kube-system - Function: metalk8s_kubernetes.namespace_annotation_present - Result: Changed Started: - 19:40:54.468944 Duration: 269.948 ms

Summary for bootstrap.revolucionmusic.com_master
-------------
Succeeded: 13 (changed=12)
Failed:     2
-------------
Total states run:     15
Total run time:  402.339 s
time="2019-09-16T21:40:57+02:00" level=fatal msg="execing command in container failed: command terminated with exit code 1"
<< END >>
```

Any idea of how to proceed or face this issue?
Thank you

**Comment by gdemonet** [comment]
Hello @JavierAbrego, thank you for trying MetalK8s and your extensive report.

> After facing quite a lot of issues in the process I was able to build the iso

Would you mind explaining briefly the issues you faced (with reproduction steps if applicable), if you can recall them? It would greatly help us improve the user experience. We develop actively the `development/2.4` branch, and are not aware of any issue w.r.t building the ISO (for this purpose, we run `./doit.sh iso`).

Can you also join a diff of the changes you had to add in `storage-operator/go.mod`/`go.sum` please? It could help us understand what was failing in your configuration.

> I prepared the machine as follows: [...]

There was nothing wrong with your preparation. Small mistake on our side however (see #1703), documentation should have asked for a `/srv/scality/metalk8s-2.4.0-dev` instead of `2.0.0`. This should not hurt the deployment experience however, as the `bootstrap.sh` script will automatically mount `/root/metalk8s.iso` at the desired mountpoint (which is `/srv/scality/metalk8s-2.4.0-dev`).

> Any idea of how to proceed or face this issue?

It seems this issue is known by some of us, though we failed to create an issue for it before. It is actually a manifestation of unreliable behaviour (which we call informally _flaky_, hence the label on this issue): please try to run `/srv/scality/metalk8s-2.0.0-dev/bootstrap.sh` again, it should proceed further.

If it doesn't, we will need more details. For this, you can run, on your Bootstrap node, the following command:

```
sudo sosreport --all-logs -o metalk8s -kmetalk8s.podlogs=True -o containerd -kcontainerd.all=True -kcontainerd.logs=True --batch
```

It will create a tarball in `/var/tmp/`, please join it to your answer along with the script output in case it fails again.

Thanks!

**Comment by JavierAbrego** [comment]
Thank you for your fast response.

> Can you also join a diff of the changes you had to add in storage-operator/go.mod/go.sum please? It could help us understand what was failing in your configuration.

I removed the directory but basically once installed the dependencies when executing doit.sh The script got stuck on obtaining the thrift dependency 
```fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out```

Similar to what was happening in the terraform project a couple of weeks ago
https://github.com/hashicorp/terraform/issues/22664


>  try to run /srv/scality/metalk8s-2.0.0-dev/bootstrap.sh again, it should proceed further.

I run it again with no luck,  this is the output

```
> Pre-minion system tests... done [0s]
> Disabling Salt minion service... done [0s]
> Stopping Salt minion service... done [1s]
> Configuring local YUM repositories... done [0s]
> Installing Salt minion... done [1s]
> Installing genisoimage... done [0s]
> Configuring Salt minion to run in local mode... done [6s]
> Calculating Salt grains in local mode... done [3s]
> Deploying early-stage bootstrap node in local mode (this may take a while)... done [113s]
> Syncing Utility modules on Salt master... done [1s]
> Syncing Pillar modules on Salt master... done [2s]
> Syncing Runner modules on Salt master... done [2s]
> Syncing Execution modules on Salt master... done [2s]
> Accepting bootstrap minion key on Salt master... done [7s]
> Refreshing all modules and data on bootstrap minion... done [4s]
> Deploying bootstrap node (this may take a while)... fail [44s]

Failure while running step 'Deploying bootstrap node (this may take a while)'

Command: crictl exec -i bb854ec12bc05077c6273e5298947841dc1d6320a42549af5b36daade4d4f795 salt-run --state-output=mixed state.orchestrate metalk8s.orchestrate.bootstrap saltenv=metalk8s-2.4.0-dev pillar={   'bootstrap_id': 'bootstrap.revolucionmusic.com' }

Output:

<< BEGIN >>
[ERROR   ] {u'ret': {u'bootstrap.revolucionmusic.com': [u"Rendering SLS 'metalk8s-2.4.0-dev:metalk8s.kubernetes.sa.advertised' failed: Jinja variable 'None' has no attribute 'get'", u'Rendering SLS \'metalk8s-2.4.0-dev:metalk8s.kubernetes.apiserver.cryptconfig\' failed: Jinja error: argument of type \'NoneType\' is not iterable\nTraceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "<template>", line 14, in top-level template code\nTypeError: argument of type \'NoneType\' is not iterable\n\n; line 14\n\n---\n[...]\n  - .installed\n\n{% set encryption_source_path = \'/etc/metalk8s/crypt/apiserver.key\' %}\n{% set encryption_k8s_path = \'/etc/kubernetes/encryption.conf\' %}\n\n{% if \'apiserver_key\' not in pillar.metalk8s.private %}    <======================\n\n{% set encryption_key = salt[\'random.get_str\'](32) | base64_encode %}\n\nCreate encryption configuration from scratch:\n  file.managed:\n[...]\n---']}, u'out': u'highstate'}
bootstrap.revolucionmusic.com_master:
  Name: saltutil.sync_all - Function: salt.runner - Result: Changed Started: - 07:58:40.853601 Duration: 1257.222 ms
  Name: saltutil.sync_roster - Function: salt.runner - Result: Changed Started: - 07:58:42.111066 Duration: 683.579 ms
  Name: metalk8s_saltutil.sync_auth - Function: salt.runner - Result: Changed Started: - 07:58:42.794971 Duration: 665.236 ms
  Name: saltutil.sync_all - Function: salt.function - Result: Changed Started: - 07:58:43.460506 Duration: 1325.153 ms
  Name: Deploy CA role on bootstrap minion - Function: salt.state - Result: Changed Started: - 07:58:44.786686 Duration: 10912.822 ms
----------
          ID: Bring bootstrap minion to highstate
    Function: salt.state
      Result: False
     Comment: Run failed on minions: bootstrap.revolucionmusic.com
     Started: 07:58:55.701544
    Duration: 15325.785 ms
     Changes:
              bootstrap.revolucionmusic.com:
                  Data failed to compile:
              ----------
                  Rendering SLS 'metalk8s-2.4.0-dev:metalk8s.kubernetes.sa.advertised' failed: Jinja variable 'None' has no attribute 'get'
              ----------
                  Rendering SLS 'metalk8s-2.4.0-dev:metalk8s.kubernetes.apiserver.cryptconfig' failed: Jinja error: argument of type 'NoneType' is not iterable
              Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 14, in top-level template code
              TypeError: argument of type 'NoneType' is not iterable

              ; line 14

              ---
              [...]
                - .installed

              {% set encryption_source_path = '/etc/metalk8s/crypt/apiserver.key' %}
              {% set encryption_k8s_path = '/etc/kubernetes/encryption.conf' %}

              {% if 'apiserver_key' not in pillar.metalk8s.private %}    <======================

              {% set encryption_key = salt['random.get_str'](32) | base64_encode %}

              Create encryption configuration from scratch:
                file.managed:
              [...]
              ---
  Name: Generate etcd client certs for salt master - Function: salt.state - Result: Clean Started: - 07:59:11.027958 Duration: 7766.351 ms
----------
          ID: Wait for API server to be available
    Function: http.wait_for_successful_query
        Name: https://91.121.87.160:6443/healthz
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Bring bootstrap minion to highstate
     Started: 07:59:18.798096
    Duration: 0.037 ms
     Changes:
----------
          ID: Configure bootstrap Node object
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Wait for API server to be available
     Started: 07:59:18.799630
    Duration: 0.035 ms
     Changes:
----------
          ID: Update pillar on bootstrap minion after highstate
    Function: salt.function
        Name: saltutil.refresh_pillar
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Configure bootstrap Node object
     Started: 07:59:18.801140
    Duration: 0.034 ms
     Changes:
----------
          ID: Update mine from bootstrap minion
    Function: salt.function
        Name: mine.update
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Update pillar on bootstrap minion after highstate, metalk8s.orchestrate.bootstrap.Configure bootstrap Node object
     Started: 07:59:18.803354
    Duration: 0.034 ms
     Changes:
----------
          ID: Deploy Kubernetes objects
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Wait for API server to be available
     Started: 07:59:18.804084
    Duration: 0.034 ms
     Changes:
----------
          ID: Precheck for MetalK8s UI
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Deploy Kubernetes objects
     Started: 07:59:18.805436
    Duration: 0.034 ms
     Changes:
----------
          ID: Deploy MetalK8s UI
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Precheck for MetalK8s UI
     Started: 07:59:18.806799
    Duration: 0.033 ms
     Changes:
----------
          ID: Store MetalK8s version in annotations
    Function: metalk8s_kubernetes.namespace_annotation_present
        Name: kube-system
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.bootstrap.Wait for API server to be available
     Started: 07:59:18.835011
    Duration: 0.038 ms
     Changes:

Summary for bootstrap.revolucionmusic.com_master
------------
Succeeded: 6 (changed=4)
Failed:    9
------------
Total states run:    15
Total run time:  37.936 s
time="2019-09-17T09:59:19+02:00" level=fatal msg="execing command in container failed: command terminated with exit code 1"
<< END >>

This script will now exit
```
The output of 
```sudo sosreport --all-logs -o metalk8s -kmetalk8s.podlogs=True -o containerd -kcontainerd.all=True -kcontainerd.logs=True --batch```

is in the link below

https://drive.google.com/open?id=15jg9Unt3SKEdE8Jy-xPQ_rlRAhIJuMiZ

Let me know if you need additional details...
Thanks,

**Comment by TeddyAndrieux** [comment]
@JavierAbrego thanks for all the output and the sosreport archive.

For you deployment issue seems you got this #1706 
To fix your deployment you should either run the mark-control-plane state manually
```
crictl exec -it $(crictl ps -q --label io.kubernetes.container.name=salt-master) salt-run state.sls metalk8s.kubernetes.mark-control-plane saltenv=metalk8s-2.4.0-dev pillar="{'mark_control_plane_hostname': 'bootstrap.revolucionmusic.com'}"
```
Or you need to use the hostname as minion_id since the issue is not fixed

**Comment by NicolasT** [comment]
@JavierAbrego With regard to the build issues you were encountering: this appears to be due to https://github.com/operator-framework/operator-sdk/issues/1873, which we did not run into on our development machines because we have the no-longer available package available in our local `GOPATH`s already, nor in our CI infrastructure where we also apply some caching to not always pull all the sources from the internet.

We have a patch in progress to resolve this.

**Comment by NicolasT** [comment]
@JavierAbrego The build issue should be resolved now in all relevant `development/*` branches. There's a patch queued for the other issue you were facing (#1706) as part of #1712. These patches should land soon, at which point we'll cut a *2.4.0-beta1* release. For more information about the objectives of this release, see https://github.com/scality/metalk8s/milestone/15

**Comment by NicolasT** [comment]
@JavierAbrego Is your issue solved? If that's the case, please close this ticket :)

Thanks again for reaching out!

**Comment by JavierAbrego** [comment]
Thank you I didn't have the chance to test again the installation process. So, yes I'm closing the issue.
