### ISSUE TITLE
Deploying bootstrap on multi-nodes env may fail due to etcd timeout

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#1934]
**Component**:

'salt', 'ci'

**What happened**:

While bootstrapping the first node of the multi-nodes env (step `Start the bootstrap process in bootstrap node`), the process failed in this build https://eve.devsca.com/github/scality/metalk8s/#/builders/1/builds/13620 with the following error:

```
> Accepting bootstrap minion key on Salt master...
No minions matched the target. No command was sent, no jid was assigned.
metalk8s-uj0ba-bootstrap.novalocal_master:
  Name: salt/auth - Function: salt.wait_for_event - Result: Changed Started: - 13:59:28.123427 Duration: 2055.152 ms
  Name: key.accept - Function: salt.wheel - Result: Changed Started: - 13:59:30.179220 Duration: 2794.483 ms
  Name: metalk8s_saltutil.wait_minions - Function: salt.runner - Result: Changed Started: - 13:59:32.974561 Duration: 15355.829 ms

Summary for metalk8s-uj0ba-bootstrap.novalocal_master
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:  20.205 s
> Refreshing all modules and data on bootstrap minion...
local:
    ----------
    beacons:
    clouds:
    engines:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    thorium:
    utils:
> Deploying bootstrap node (this may take a while)...
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[ERROR   ] Exception when calling ExtensionsV1beta1Api->create_custom_resource_definition
Traceback (most recent call last):
  File "/var/cache/salt/master/extmods/modules/metalk8s_kubernetes.py", line 2279, in create_customresourcedefinition
    body=body)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/apiextensions_v1beta1_api.py", line 59, in create_custom_resource_definition
    (data) = self.create_custom_resource_definition_with_http_info(body, **kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/apiextensions_v1beta1_api.py", line 144, in create_custom_resource_definition_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 364, in request
    body=body)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'date': 'Thu, 17 Oct 2019 14:02:28 GMT', 'content-length': '122', 'content-type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"etcdserver: request timed out","code":500}


[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/master/extmods/states/metalk8s_kubernetes.py", line 1557, in customresourcedefinition_present
    **kwargs)
  File "/var/cache/salt/master/extmods/modules/metalk8s_kubernetes.py", line 2290, in create_customresourcedefinition
    raise CommandExecutionError(exc)
CommandExecutionError: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'date': 'Thu, 17 Oct 2019 14:02:28 GMT', 'content-length': '122', 'content-type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"etcdserver: request timed out","code":500}



[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
[WARNING ] The object already has a name attribute, overwriting it with the one defined inside of salt
```

See full log here: [stdio.zip](https://github.com/scality/metalk8s/files/3742589/stdio.zip)

**What was expected**:

It should have run smoothly.

**Steps to reproduce**

No idea since it's a flaky.

**Resolution proposal** (optional):

**Comment by TeddyAndrieux** [comment]
Old one never seen since a long time so let's close it for now
