### ISSUE TITLE
chart rendering fails due to unknown flag using helm version 3

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2214]
**Component**:

'charts'

**Why this is needed**:

Developers should be able to add and render helm charts normally but currently, rendering fails with the below output.

```
Error: unknown flag: --name
Traceback (most recent call last):
  File "./charts/render.py", line 124, in <module>
    main()
  File "./charts/render.py", line 98, in main
    path,
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)subprocess.CalledProcessError: Command '['helm', 'template', '--name', 'prometheus-operator', '--namespace', 'metalk8s-monitoring', '--values', 'charts/prometheus-operator.yaml', 'charts/prometheus-operator']' returned non-zero exit status 1.
```

**What should be done**:

As of helm 3, the `--name` flag is no more and it looks to have been replaced as a positional argument.

```
New Usage:
helm template [NAME] [CHART] [flags]
```

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Could make sense to port the rendering script into the `doit` buildchain IMO, even though the output should be committed to history.

Also, not sure if we need/want to handle Helm 3 at that stage. Is the chart update requiring this? We could enforce a version check in the `doit` task, or provide a compatibility layer, if you really want to.

**Comment by NicolasT** [comment]
I'd stick to Helm 2 right now as well (and maybe add a pre-check). Supporting 3 needs more investigation.
