### ISSUE TITLE
Build of salt-master image is broken

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2220]
**Component**: build

**What happened**:
At build time, the salt-master image build is failing

**What was expected**:
Build went successfully and the salt-master image is present. 

**Steps to reproduce**:
Remove the salt-master image from your local cache, then try to build the images
```
./doit.sh images
```
You can also trigger a build in the CI.

**Resolution proposal** (optional):

**Comment by alexandre-allard** [comment]
Looks like the issue is when we try to install etcd3 with pip:
```
#  pip install "etcd3 != 0.11.0"
Collecting etcd3!=0.11.0
  Downloading https://files.pythonhosted.org/packages/30/1b/6402bb034afd85a33f3fe0ea064a496f3f96917e21ddefbe70c89735ccbf/etcd3-0.11.1.tar.gz (63kB)
    100% |################################| 71kB 1.9MB/s
Collecting grpcio>=1.24.0 (from etcd3!=0.11.0)
  Downloading https://files.pythonhosted.org/packages/c3/a1/89b7905c9540ad2eac024630abece06d2d563b5fb06e10f6597dcd33972f/grpcio-1.27.0.tar.gz (16.9MB)
    100% |################################| 16.9MB 72kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-glvgiO/grpcio/setup.py", line 191, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-build-glvgiO/grpcio/setup.py", line 152, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-glvgiO/grpcio/
```

**Comment by NicolasT** [comment]
This seems fixed?

**Comment by slaperche-scality** [comment]
It is.
The PR was merged and was referencing the issue correctly (but it haven't been auto-closed though…)
