### ISSUE TITLE
Bump Prometheus-operator version to 8.13.0

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2430]
**Component**:

'charts', 'monitoring', 'prometheus-operator'

**Why this is needed**:

We need to update the chart version we currently deploy for Prometheus-operator to the latest stable release.

**What should be done**:

- Bump the version of the chart to 8.13.0
- Ensure grafana-piechart-panel plugin is present (no missing plugins)
- Check and validate that Grafana dashboards have data

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by Ebaneck** [comment]
Bumping the Prometheus-operator version to 8.13.0 results in the following
```
> Deploying bootstrap node (this may take a while)...[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/master/extmods/states/metalk8s_kubernetes.py", line 132, in object_present
    **kwargs
  File "/var/cache/salt/master/extmods/modules/metalk8s_kubernetes.py", line 158, in method
    force_custom_object=action in ['retrieve', 'delete', 'update']
  File "/var/cache/salt/master/extmods/modules/metalk8s_kubernetes.py", line 54, in _extract_obj_and_kind_info
    raise CommandExecutionError('Invalid manifest: {!s}'.format(exc))
CommandExecutionError: Invalid manifest: Unsupported attribute preserveUnknownFields for "V1beta1CustomResourceDefinitionSpec" object.
```
This is likely due to the fact that the python2-kubernetes version we currently use does not have support for `preserve_unknown_fields(bool)` which was recently introduced in v11.0.0 here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1beta1CustomResourceDefinitionSpec.md.
