### ISSUE TITLE
deploy_node fails when anything other then node role Ubuntu 18.04

### ISSUE THREAD

**Issue by marcboivin** [scality/metalk8s#2442]
**Component**:
salt, ubuntu

**What happened**:
Trying to deploy a node with any component other than node fails. 

>               ----------
                        ID: Install salt-minion
                  Function: metalk8s_package_manager.installed
                      Name: salt-minion
                    Result: False
                   Comment: An exception occurred in this state: Traceback (most recent call last):
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/state.py", line 1919, in call
                                **cdata['kwargs'])
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/loader.py", line 1918, in wrapper
                                return f(*args, **kwargs)
                              File "/var/tmp/.root_e2db7b_salt/running_data/var/cache/salt/minion/extmods/states/metalk8s_package_manager.py", line 32, in installed
                                dep_list = __salt__['metalk8s_package_manager.list_pkg_dependents'](
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/loader.py", line 1175, in __getitem__
                                func = super(LazyLoader, self).__getitem__(item)
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/utils/lazy.py", line 108, in __getitem__
                                raise KeyError(key)
                            KeyError: 'metalk8s_package_manager.list_pkg_dependents'
                   Started: 12:07:38.050273
                  Duration: 2178.364 ms
                   Changes:

**What was expected**:
Deployment to complete normally
**Steps to reproduce**
Version 2.4.3 complete install configure a node with the GUI and try to deploy with the GUI. 
**Resolution proposal** (optional):

> mbi-node75_master:
----------
          ID: Deploy salt-minion on a new node
    Function: salt.state
      Result: False
     Comment: Run failed on minions: mbi-node72
     Started: 12:06:37.459266
    Duration: 63390.747 ms
     Changes:
              mbi-node72:
              ----------
                        ID: Configure metalk8s-salt_ubuntu1804 repository
                  Function: file.managed
                      Name: /etc/apt/sources.list.d/metalk8s-salt_ubuntu1804.list
                    Result: True
                   Comment: File /etc/apt/sources.list.d/metalk8s-salt_ubuntu1804.list is in the correct state
                   Started: 12:07:37.782290
                  Duration: 146.959 ms
                   Changes:
              ----------
                        ID: Configure metalk8s-scality repository
                  Function: file.managed
                      Name: /etc/apt/sources.list.d/metalk8s-scality.list
                    Result: True
                   Comment: File /etc/apt/sources.list.d/metalk8s-scality.list is in the correct state
                   Started: 12:07:37.929454
                  Duration: 21.937 ms
                   Changes:
              ----------
                        ID: Configure metalk8s-bionic-updates repository
                  Function: file.managed
                      Name: /etc/apt/sources.list.d/metalk8s-bionic-updates.list
                    Result: True
                   Comment: File /etc/apt/sources.list.d/metalk8s-bionic-updates.list is in the correct state
                   Started: 12:07:37.951579
                  Duration: 21.65 ms
                   Changes:
              ----------
                        ID: Configure metalk8s-bionic repository
                  Function: file.managed
                      Name: /etc/apt/sources.list.d/metalk8s-bionic.list
                    Result: True
                   Comment: File /etc/apt/sources.list.d/metalk8s-bionic.list is in the correct state
                   Started: 12:07:37.973415
                  Duration: 21.752 ms
                   Changes:
              ----------
                        ID: Configure metalk8s-bionic-backports repository
                  Function: file.managed
                      Name: /etc/apt/sources.list.d/metalk8s-bionic-backports.list
                    Result: True
                   Comment: File /etc/apt/sources.list.d/metalk8s-bionic-backports.list is in the correct state
                   Started: 12:07:37.995354
                  Duration: 21.79 ms
                   Changes:
              ----------
                        ID: Configure metalk8s-kubernetes-xenial repository
                  Function: file.managed
                      Name: /etc/apt/sources.list.d/metalk8s-kubernetes-xenial.list
                    Result: True
                   Comment: File /etc/apt/sources.list.d/metalk8s-kubernetes-xenial.list is in the correct state
                   Started: 12:07:38.017329
                  Duration: 23.906 ms
                   Changes:
              ----------
                        ID: Add APT metalk8s repositories preferences
                  Function: file.managed
                      Name: /etc/apt/preferences.d/1001-metalk8s
                    Result: True
                   Comment: File /etc/apt/preferences.d/1001-metalk8s is in the correct state
                   Started: 12:07:38.041430
                  Duration: 1.914 ms
                   Changes:
              ----------
                        ID: Repositories configured
                  Function: test.succeed_without_changes
                    Result: True
                   Comment: Success!
                   Started: 12:07:38.048574
                  Duration: 0.439 ms
                   Changes:
              ----------
                        ID: Install salt-minion
                  Function: metalk8s_package_manager.installed
                      Name: salt-minion
                    Result: False
                   Comment: An exception occurred in this state: Traceback (most recent call last):
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/state.py", line 1919, in call
                                **cdata['kwargs'])
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/loader.py", line 1918, in wrapper
                                return f(*args, **kwargs)
                              File "/var/tmp/.root_e2db7b_salt/running_data/var/cache/salt/minion/extmods/states/metalk8s_package_manager.py", line 32, in installed
                                dep_list = __salt__['metalk8s_package_manager.list_pkg_dependents'](
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/loader.py", line 1175, in __getitem__
                                func = super(LazyLoader, self).__getitem__(item)
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/utils/lazy.py", line 108, in __getitem__
                                raise KeyError(key)
                            KeyError: 'metalk8s_package_manager.list_pkg_dependents'
                   Started: 12:07:38.050273
                  Duration: 2178.364 ms
                   Changes:
              ----------
                        ID: Configure salt minion
                  Function: file.managed
                      Name: /etc/salt/minion.d/99-metalk8s.conf
                    Result: True
                   Comment: File /etc/salt/minion.d/99-metalk8s.conf is in the correct state
                   Started: 12:07:40.234564
                  Duration: 24.228 ms
                   Changes:
              ----------
                        ID: Restart salt-minion
                  Function: cmd.wait
                      Name: salt-call --local service.restart salt-minion > /dev/null
                    Result: True
                   Comment:
                   Started: 12:07:40.259150
                  Duration: 0.614 ms
                   Changes:
              ----------
                        ID: Wait until salt-minion restarted
                  Function: module.wait
                    Result: True
                   Comment:
                   Started: 12:07:40.263582
                  Duration: 0.407 ms
                   Changes:
              ----------
                        ID: Ensure salt-minion running
                  Function: service.running
                      Name: salt-minion
                    Result: False
                   Comment: The named service salt-minion is not available
                   Started: 12:07:40.269929
                  Duration: 35.139 ms
                   Changes:
              ----------
                        ID: Ensure salt-minion running
                  Function: module.run
                    Result: False
                   Comment: One or more requisite failed: metalk8s.salt.minion.running.Ensure salt-minion running
                   Started: 12:07:40.306755
                  Duration: 0.021 ms
                   Changes:
              ----------
                        ID: Install sos report and custom plugins
                  Function: metalk8s_package_manager.installed
                      Name: metalk8s-sosreport
                    Result: False
                   Comment: An exception occurred in this state: Traceback (most recent call last):
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/state.py", line 1919, in call
                                **cdata['kwargs'])
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/loader.py", line 1918, in wrapper
                                return f(*args, **kwargs)
                              File "/var/tmp/.root_e2db7b_salt/running_data/var/cache/salt/minion/extmods/states/metalk8s_package_manager.py", line 32, in installed
                                dep_list = __salt__['metalk8s_package_manager.list_pkg_dependents'](
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/loader.py", line 1175, in __getitem__
                                func = super(LazyLoader, self).__getitem__(item)
                              File "/var/tmp/.root_e2db7b_salt/py2/salt/utils/lazy.py", line 108, in __getitem__
                                raise KeyError(key)
                            KeyError: 'metalk8s_package_manager.list_pkg_dependents'
                   Started: 12:07:40.307019
                  Duration: 17.221 ms
                   Changes:

              Summary for mbi-node72
              -------------
              Succeeded: 11
              Failed:     4
              -------------
              Total states run:     15
              Total run time:    2.516 s
----------
          ID: Accept key
    Function: module.run
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Deploy salt-minion on a new node
     Started: 12:07:40.852510
    Duration: 0.02 ms
     Changes:
----------
          ID: Wait minion available
    Function: salt.runner
        Name: metalk8s_saltutil.wait_minions
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Accept key
     Started: 12:07:40.853344
    Duration: 0.022 ms
     Changes:
----------
          ID: Set grains
    Function: salt.state
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Wait minion available
     Started: 12:07:40.854781
    Duration: 0.02 ms
     Changes:
----------
          ID: Refresh the mine
    Function: salt.function
        Name: mine.update
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Wait minion available
     Started: 12:07:40.855438
    Duration: 0.015 ms
     Changes:
----------
          ID: Cordon the node
    Function: metalk8s_cordon.node_cordoned
        Name: mbi-node72
      Result: True
     Comment: The node mbi-node72 is already cordoned
     Started: 12:07:40.856015
    Duration: 68.188 ms
     Changes:
----------
          ID: Drain the node
    Function: metalk8s_drain.node_drained
        Name: mbi-node72
      Result: True
     Comment: Eviction complete.
     Started: 12:07:40.926745
    Duration: 108.72 ms
     Changes:
              ----------
              mbi-node72:
                  ----------
                  mbi-node72:
                      drained
----------
          ID: Sync module on the node
    Function: salt.function
        Name: saltutil.sync_all
      Result: False
     Comment:
     Started: 12:07:41.036057
    Duration: 118.191 ms
     Changes:
----------
          ID: Refresh and check pillar before etcd deployment
    Function: salt.function
        Name: metalk8s.check_pillar_keys
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Sync module on the node
     Started: 12:07:41.156261
    Duration: 0.029 ms
     Changes:
----------
          ID: Install etcd node
    Function: salt.state
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Refresh and check pillar before etcd deployment
     Started: 12:07:41.158548
    Duration: 0.031 ms
     Changes:
----------
          ID: Register the node into etcd cluster
    Function: salt.runner
        Name: state.orchestrate
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Install etcd node
     Started: 12:07:41.160078
    Duration: 0.029 ms
     Changes:
----------
          ID: Wait for API server to be available before highstate
    Function: http.wait_for_successful_query
        Name: https://127.0.0.1:7443/healthz
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Register the node into etcd cluster
     Started: 12:07:41.163189
    Duration: 0.033 ms
     Changes:
----------
          ID: Refresh and check pillar before highstate
    Function: salt.function
        Name: metalk8s.check_pillar_keys
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Sync module on the node, metalk8s.orchestrate.deploy_node.Wait for API server to be available before highstate
     Started: 12:07:41.165894
    Duration: 0.019 ms
     Changes:
----------
          ID: Run the highstate
    Function: salt.state
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Set grains, metalk8s.orchestrate.deploy_node.Refresh and check pillar before highstate, metalk8s.orchestrate.deploy_node.Refresh the mine
     Started: 12:07:41.169111
    Duration: 0.018 ms
     Changes:
----------
          ID: Wait for API server to be available
    Function: http.wait_for_successful_query
        Name: https://127.0.0.1:7443/healthz
      Result: True
     Comment: Match text "ok" was found.Status 200 was found, as specified.
		body: ok
		status: 200
		text: ok
     Started: 12:07:41.169251
    Duration: 26.886 ms
     Changes:
----------
          ID: Uncordon the node
    Function: metalk8s_cordon.node_uncordoned
        Name: mbi-node72
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Run the highstate
     Started: 12:07:41.199153
    Duration: 0.023 ms
     Changes:
----------
          ID: Kill kube-controller-manager on all master nodes
    Function: salt.function
        Name: ps.pkill
      Result: False
     Comment: One or more requisite failed: metalk8s.orchestrate.deploy_node.Run the highstate
     Started: 12:07:41.199854
    Duration: 0.02 ms
     Changes:

Summary for mbi-node75_master
-------------
Succeeded:  3 (changed=1)
Failed:    14
-------------
Total states run:     17
Total run time:   63.713 s

**Comment by marcboivin** [comment]
So digging into it, it seems that it fail with :

/usr/bin/python2.7 /var/tmp/.root_e2db7b_salt/salt-call --retcode-passthrough --local --metadata --out json -l quiet -c /var/tmp/.root_e2db7b_salt -- state.pkg /var/tmp/.root_e2db7b_salt/salt_state.tgz test=None pkg_sum=06ae3a35836742076

Passed invalid arguments: pkg() takes at least 3 arguments (3 given).

Usage:

    Execute a packaged state run, the packaged state run will exist in a
    tarball available locally. This packaged state
    can be generated using salt-ssh.

    CLI Example:

    .. code-block:: bash

        salt '*' state.pkg /tmp/salt_state.tgz 760a9353810e36f6d81416366fc426dc md5

**Comment by gdemonet** [comment]
Hi @marcboivin, thanks again for the detailed report.

At the moment, we merely started adding support for Ubuntu 18.04 in MetalK8s, and it's not yet part of our CI, so probably not working as you would expect.
As of today, version 2 of MetalK8s only supports CentOS/RHEL 7.6 or higher.

The "Ubuntu support" project can be tracked [here](https://github.com/scality/metalk8s/projects/26). We can't give any commitment as to when this will be delivered, given the other topics we're currently working on.
If you, or anyone, wants to contribute on this matter, we'd be glad and will make sure to guide you through the codebase!

I'll keep this issue opened, and we'll update its status once progress has been made.

**Comment by marcboivin** [comment]
Well, considering the state it is in, it's definitely usable. So yeah definitely, I'll look into it.

**Comment by marcboivin** [comment]
Are issues the best place to talk? I think I figure some etcd scenarios that are making the cluster split brain and rendering the whole stack flaky.

**Comment by NicolasT** [comment]
Hello @marcboivin,

Thanks for following up :+1: We experienced some issues going from a single-node cluster (~ etcd-ensemble) to two-node (expanding the etcd ensemble as well). Going from one member to two is somewhat of a tricky operation in a quorum-based system, so we're looking at ways to make this operation more resilient.

However, this scenario should *not* result in split-brain clusters, so we'd be interested to learn how this happened in your cluster... I believe this would definitely warrant another issue on GitHub, because that'd be a bug.

In general, issues are fine to discuss, so please do. For 'chatter', we're considering to create a public room on our Slack. Will keep you posted once this is set up.

**Comment by NicolasT** [comment]
Hello again @marcboivin,

Getting back to the 'communication channels' question you raised: we're currently unable to open up our internal Slack for external contributors. As such, I suggest we stick with GitHub for now (and maybe Discussions if we get access to that feature on this repository).

Thank you!
