### ISSUE TITLE
Bootstrap may fail if epel repo enabled with some priority

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2704]
**Component**:

'salt'

**What happened**:

When running bootstrap with epel repo enable and has some yum priority https://wiki.centos.org/PackageManagement/Yum/Priorities set on it, salt from epel repository is installed (2015.x).

So bootstrap fail because some expected function not here (like `fopen`)

```
[CRITICAL] Rendering SLS 'base:metalk8s.salt.minion.local' failed: Jinja error: 'module' object has no attribute 'fopen'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 364, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 2, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/metalk8s.py", line 211, in get_archives
    info = archive_info_from_tree(archive)
  File "/var/cache/salt/minion/extmods/modules/metalk8s.py", line 158, in archive_info_from_tree
    with salt.utils.files.fopen(product_txt) as fd:
AttributeError: 'module' object has no attribute 'fopen'

; line 2

---
{%- from "metalk8s/map.jinja" import metalk8s with context %}
{%- set archives = salt.metalk8s.get_archives() %}    <======================

Configure salt minion for local mode:
  file.serialize:
    - name: /etc/salt/minion.d/99-metalk8s-local.conf
    - user: root
[...]
---
local:
    Data failed to compile:
----------
    Rendering SLS 'base:metalk8s.salt.minion.local' failed: Jinja error: 'module' object has no attribute 'fopen'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 364, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 2, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/metalk8s.py", line 211, in get_archives
    info = archive_info_from_tree(archive)
  File "/var/cache/salt/minion/extmods/modules/metalk8s.py", line 158, in archive_info_from_tree
    with salt.utils.files.fopen(product_txt) as fd:
AttributeError: 'module' object has no attribute 'fopen'

; line 2

---
{%- from "metalk8s/map.jinja" import metalk8s with context %}
{%- set archives = salt.metalk8s.get_archives() %}    <======================

Configure salt minion for local mode:
  file.serialize:
    - name: /etc/salt/minion.d/99-metalk8s-local.conf
    - user: root
[...]
---
<< END >>

This script will now exit
```

**Workaround**:

Disable epel repository (as this repository is not needed at all for MetalK8s) to perform bootstrap or just unset the priority on epel repository.

**What was expected**:

Working bootstrap and Salt minion from our repo installed either:

- If salt-minion already installed in another version (may be downgraded or upgraded in bootstrap script)
- If other salt-minion packages available in another repo (likely 2015.x in epel repo even if a priority is set on this epel repository)

**Steps to reproduce**

Install the yum priority plugin, enable epel repository and set priority on epel repository to something between 1 and 98 and then bootstrap

```
yum install epel-release
yum install yum-plugin-priorities
vim /etc/yum.repos.d/epel.repo # set `priority=10` for epel repo
```

**Resolution proposal** (optional):

Force the salt-minion version we install in bootstrap script

**Comment by TeddyAndrieux** [comment]
I tried to reproduce but in my case it's always the newest version available that get installed (that may be an issue if some repo with newer salt version available)

We need more information to try to reproduce this issue (anyway the resolution proposal still make sense)
