### ISSUE TITLE
Upgrade from 2.5.1 to 2.6.0-dev fails

### ISSUE THREAD

**Issue by rachedbenmustapha** [scality/metalk8s#2811]
**Component**: upgrade

**What happened**:

Upgrade failed and left the cluster in a state that can't be operated anymore for operations relying on salt. Purely kubernetes-level functionality still operational.

```
# ./upgrade.sh   --destination-version 2.6.0-dev
> Performing Pre-Upgrade checks... done [5s]
> Upgrading bootstrap... fail [172s]

Failure while running step 'Upgrading bootstrap'

Command: upgrade_bootstrap

Output:

<< BEGIN >>
local:
    ----------
    beacons:
    clouds:
    engines:
    executors:
    grains:
    log_handlers:
    matchers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    serializers:
    states:
    thorium:
    utils:
[INFO    ] Runner completed: 20200922002435478721
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [Refresh CA minion] at time 00:24:35.869865
[INFO    ] Executing state salt.state for [Refresh CA minion]
[INFO    ] States ran successfully. No changes made to bootstrap.
[INFO    ] Completed state [Refresh CA minion] at time 00:25:29.483018 (duration_in_ms=53613.153)
[INFO    ] Running state [Ensure all apiservers serve a certificate for 127.0.0.1] at time 00:25:29.484053
[INFO    ] Executing state salt.state for [Ensure all apiservers serve a certificate for 127.0.0.1]
[INFO    ] States ran successfully. No changes made to master-1, master-0, bootstrap.
[INFO    ] Completed state [Ensure all apiservers serve a certificate for 127.0.0.1] at time 00:26:36.362284 (duration_in_ms=66878.229)
[INFO    ] Running state [Prepare for Salt Master upgrade] at time 00:26:36.363971
[INFO    ] Executing state salt.state for [Prepare for Salt Master upgrade]
[INFO    ] States ran successfully. No changes made to bootstrap.
[INFO    ] Completed state [Prepare for Salt Master upgrade] at time 00:26:47.900073 (duration_in_ms=11536.102)
[INFO    ] Running state [https://127.0.0.1:7443/healthz] at time 00:26:47.901551
[INFO    ] Executing state http.wait_for_successful_query for [https://127.0.0.1:7443/healthz]
[INFO    ] Match text "ok" was found. Status 200 was found.
[INFO    ] Completed state [https://127.0.0.1:7443/healthz] at time 00:26:47.945212 (duration_in_ms=43.661)
bootstrap_master:
----------
          ID: Refresh CA minion
    Function: salt.state
      Result: True
     Comment: States ran successfully. No changes made to bootstrap.
     Started: 00:24:35.869865
    Duration: 53613.153 ms
     Changes:   
----------
          ID: Ensure all apiservers serve a certificate for 127.0.0.1
    Function: salt.state
      Result: True
     Comment: States ran successfully. No changes made to master-1, master-0, bootstrap.
     Started: 00:25:29.484055
    Duration: 66878.229 ms
     Changes:   
----------
          ID: Prepare for Salt Master upgrade
    Function: salt.state
      Result: True
     Comment: States ran successfully. No changes made to bootstrap.
     Started: 00:26:36.363971
    Duration: 11536.102 ms
     Changes:   
----------
          ID: Wait for an API server to be available through local proxy
    Function: http.wait_for_successful_query
        Name: https://127.0.0.1:7443/healthz
      Result: True
     Comment: Match text "ok" was found. Status 200 was found.
		body: ok
		status: 200
		text: ok
     Started: 00:26:47.901551
    Duration: 43.661 ms
     Changes:   

Summary for bootstrap_master
------------
Succeeded: 4
Failed:    0
------------
Total states run:     4
Total run time: 132.071 s
[INFO    ] Runner completed: 20200922002433205798
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 404, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'ports'
[CRITICAL] Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.repo.redhat' failed: Jinja variable 'dict object' has no attribute 'ports'
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 404, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'ports'
[CRITICAL] Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.container-engine.containerd.installed' failed: Jinja variable 'dict object' has no attribute 'ports'
local:
    Data failed to compile:
----------
    Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.repo.redhat' failed: Jinja variable 'dict object' has no attribute 'ports'
----------
    Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.container-engine.containerd.installed' failed: Jinja variable 'dict object' has no attribute 'ports'
<< END >>

This script will now exit
```

After this failure, any metalk8s-related command I try to run fails with error `Failed to find a running 'salt-master' container` or error `Attempt to authenticate with the salt master failed with timeout error` - No `salt-master` pod is running.

**What was expected**:

Cluster running metalk8s 2.6.0-dev, ready to import a new solution ISO.

**Steps to reproduce**

1. Install metalk8s 2.5.1 (one-click was used, the bundled zenko worked fine, as a sanity check)
1. Build an image based on 89996a3defd263eab35f8942e9d0d021d8346daa
1. import it with `./iso-manager.sh -a ~/metalk8s/_build/metalk8s.iso`
1. Run `./upgrade.sh --destination-version 2.6.0-dev` from `/srv/scality/metalk8s-2.6.0-dev`

**Comment by gdemonet** [comment]
From the info available here, it appears you built the 2.6 ISO from the Bootstrap node, correct?
If yes, does it mean you had to install build dependencies, like Docker, on this host?

It's possible that build dependencies interfere with our upgrade tooling, at least we know it prevents a proper installation (see #2796). We will try to reproduce, though in general, we recommend building on a separate host / VM.

**Comment by rachedbenmustapha** [comment]
This was actually the second attempt, the first attempt was with the iso pre-built on another machine (an no docker on the bootstrap node), with the same result.

**Comment by alexandre-allard** [comment]
I think I've reproduced the issue on my lab.

First upgrade try failed with:
```
              ----------
                        ID: Deploy etcd master-0 to 2.6.0-dev
                  Function: salt.state
                    Result: False
                   Comment: Run failed on minions: master-0
                   Started: 13:34:03.219118
                  Duration: 2803.671 ms
                   Changes:
                            master-0:
                                Data failed to compile:
                            ----------
                                Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.repo.redhat' failed: Jinja variable 'dict object' has no attribute 'ports'
              ----------
```

Then trying to upgrade a second time gives the exact same error as Rached reported.
I think that's because the pillar is not in a good shape here, so it fails and makes all the subsequent upgrade attempts fail.

In my pillar, I have (for the endpoints):
```
# salt bootstrap pillar.get metalk8s:endpoints
bootstrap:
    ----------
    _errors:
        - U
        - n
        - a
        - b
        - l
        - e
        -
        - t
        - o
        -
        - g
        - e
        - t
        -
        - k
        - u
        - b
        - e
        - r
        - n
        - e
        - t
        - e
        - s
        -
        - e
        - n
        - d
        - p
        - o
        - i
        - n
        - t
        - s
        -
        - f
        - o
        - r
        -
        - s
        - a
        - l
        - t
        - -
        - m
        - a
        - s
        - t
        - e
        - r
        -
        - i
        - n
        -
        - n
        - a
        - m
        - e
        - s
        - p
        - a
        - c
        - e
        -
        - k
        - u
        - b
        - e
        - -
        - s
        - y
        - s
        - t
        - e
        - m
        - :
        -
        - '
        - N
        - o
        - n
        - e
        - T
        - y
        - p
        - e
        - '
        -
        - o
        - b
        - j
        - e
        - c
        - t
        -
        - h
        - a
        - s
        -
        - n
        - o
        -
        - a
        - t
        - t
        - r
        - i
        - b
        - u
        - t
        - e
        -
        - '
        - _
        - _
        - g
        - e
        - t
        - i
        - t
        - e
        - m
        - _
        - _
        - '
        - U
        - n
        - a
        - b
        - l
        - e
        -
        - t
        - o
        -
        - g
        - e
        - t
        -
        - k
        - u
        - b
        - e
        - r
        - n
        - e
        - t
        - e
        - s
        -
        - e
        - n
        - d
        - p
        - o
        - i
        - n
        - t
        - s
        -
        - f
        - o
        - r
        -
        - r
        - e
        - p
        - o
        - s
        - i
        - t
        - o
        - r
        - i
        - e
        - s
        -
        - i
        - n
        -
        - n
        - a
        - m
        - e
        - s
        - p
        - a
        - c
        - e
        -
        - k
        - u
        - b
        - e
        - -
        - s
        - y
        - s
        - t
        - e
        - m
        - :
        -
        - '
        - N
        - o
        - n
        - e
        - T
        - y
        - p
        - e
        - '
        -
        - o
        - b
        - j
        - e
        - c
        - t
        -
        - h
        - a
        - s
        -
        - n
        - o
        -
        - a
        - t
        - t
        - r
        - i
        - b
        - u
        - t
        - e
        -
        - '
        - _
        - _
        - g
        - e
        - t
        - i
        - t
        - e
        - m
        - _
        - _
        - '
    repositories:
        ----------
        _errors:
            Unable to get kubernetes endpoints for repositories in namespace kube-system:
            'NoneType' object has no attribute '__getitem__'
    salt-master:
        ----------
        _errors:
            Unable to get kubernetes endpoints for salt-master in namespace kube-system:
            'NoneType' object has no attribute '__getitem__'
```

It does not look good. :)

I tried to refresh the pillar (which put it in a good state), but it does not seem to fix the issue and the pillar is messed up again after another upgrade attempt, but it passes the step above and fails later:

```
              ----------
                        ID: Deploy etcd master-1 to 2.6.0-dev
                  Function: salt.state
                    Result: False
                   Comment: Run failed on minions: master-1
                   Started: 08:36:26.680376
                  Duration: 35604.015 ms
                   Changes:
                            master-1:
                                False
              ----------
```

I've checked the etcd cluster, everything is OK there...

**Comment by alexandre-allard** [comment]
Relaunched the upgrade this morning after reboot and it worked...

**Comment by alexandre-allard** [comment]
Currently investigating and trying to work on a fix, we think it may be related to the pillar not well refreshed at this point but the errors provided in Salt logs are not helping a lot, the endpoint objects from K8s are probably not there when the pillar is rendered and that's the cause.
