### ISSUE TITLE
Bootstrap error in generation of salt API keys 

### ISSUE THREAD

**Issue by Abhishek627** [scality/metalk8s#2967]
**Component**:  salt

**What happened**: After mounting and running bootstrap.sh, it failed in the step `Deploying early-stage bootstrap node in local mode` (version used is 2.6.0). Following this doc (https://metal-k8s.readthedocs.io/en/2.5.1/installation/bootstrap.html?highlight=bootstrap). Error given is:
```
----------
          ID: Generate Salt API certificate
    Function: x509.certificate_managed
        Name: /etc/salt/pki/api/salt-api.crt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1981, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 502, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1430, in create_certificate
                  kwargs.update(signing_policy)
              TypeError: 'NoneType' object is not iterable
     Started: 09:37:23.818065
    Duration: 3.207 ms
     Changes:   
  Name: /etc/salt/master.d/99-metalk8s.conf - Function: file.managed - Result: Clean Started: - 09:37:23.821496 Duration: 6.849 ms
  Name: /etc/salt/master.d/99-metalk8s-roots.conf - Function: file.serialize - Result: Clean Started: - 09:37:23.828540 Duration: 1.127 ms
  Name: /etc/salt - Function: file.directory - Result: Clean Started: - 09:37:23.829856 Duration: 0.92 ms
  Name: /var/cache/salt - Function: file.directory - Result: Clean Started: - 09:37:23.830957 Duration: 0.873 ms
  Name: /var/run/salt - Function: file.directory - Result: Clean Started: - 09:37:23.832017 Duration: 1.273 ms
  Name: /etc/kubernetes/manifests/salt-master.yaml - Function: metalk8s.static_pod_managed - Result: Clean Started: - 09:37:23.835391 Duration: 12.458 ms
  Name: Delay after new pod deployment - Function: module.wait - Result: Clean Started: - 09:37:23.848848 Duration: 0.639 ms
  Name: Make sure salt master container is up - Function: module.wait - Result: Clean Started: - 09:37:23.850791 Duration: 0.656 ms
----------
          ID: Wait for Salt API to answer
    Function: http.wait_for_successful_query
        Name: https://10.105.58.81:4507/
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1981, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/http.py", line 213, in wait_for_successful_query
                  raise caught_exception  # pylint: disable=E0702
              CommandExecutionError: [Errno 111] Connection refused
     Started: 09:37:23.852386
    Duration: 300002.574 ms
     Changes:   
  Name: kubectl - Function: metalk8s_package_manager.installed - Result: Clean Started: - 09:42:23.855933 Duration: 1530.88 ms
  Name: salt-minion - Function: metalk8s_package_manager.installed - Result: Clean Started: - 09:42:25.389924 Duration: 1656.176 ms
  Name: /etc/salt/minion.d/99-metalk8s.conf - Function: file.managed - Result: Clean Started: - 09:42:27.047166 Duration: 9.201 ms
  Name: salt-call --local service.restart salt-minion > /dev/null - Function: cmd.wait - Result: Clean Started: - 09:42:27.057609 Duration: 0.749 ms
  Name: Wait until salt-minion restarted - Function: test.configurable_test_state - Result: Clean Started: - 09:42:27.059381 Duration: 0.014 ms
  Name: salt-minion - Function: service.running - Result: Changed Started: - 09:42:27.060192 Duration: 636.378 ms
  Name: Ensure salt-minion running - Function: test.configurable_test_state - Result: Clean Started: - 09:42:27.701058 Duration: 2.027 ms
  Name: metalk8s-sosreport - Function: metalk8s_package_manager.installed - Result: Clean Started: - 09:42:27.704728 Duration: 1080.762 ms

Summary for local
-------------
Succeeded: 76 (changed=8)
Failed:     7
-------------
```
**What was expected**:  Bootstrap should have been successful.
**Steps to reproduce**: Clone version 2.6.0-dev, follow the doc link above. bootstrap.yaml used is of format:
```yaml
apiVersion: metalk8s.scality.com/v1alpha2
kind: BootstrapConfiguration
networks:
  controlPlane: <CIDR-notation>
  workloadPlane: <CIDR-notation>
  pods: <CIDR-notation>
  services: <CIDR-notation>
proxies:
  http: <http://proxy-ip:proxy-port>
  https: <https://proxy-ip:proxy-port>
  no_proxy:
    - <host>
    - <ip/cidr>
ca:
  minion: <hostname-of-the-bootstrap-node>
archives:
  - <path-to-metalk8s-iso>
```
**Resolution proposal** (optional):

**Comment by Abhishek627** [comment]
Did I do some step wrongly? This was deployed successfully earlier in another setup when i used minion: {{minion-ip}} instead of hostname

**Comment by Abhishek627** [comment]
After checking the hostname in bootstrap.yaml, minion_id and hostname, there were some differences in those and i made all 3 as similar. After this, cert error is gone but the api communication error is still there. 
```
          ID: Wait for Salt API to answer
    Function: http.wait_for_successful_query
        Name: https://10.105.58.111:4507/
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1981, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/http.py", line 213, in wait_for_successful_query
                  raise caught_exception  # pylint: disable=E0702
              CommandExecutionError: [Errno 111] Connection refused
     Started: 07:00:00.738299
    Duration: 300001.155 ms
     Changes:
```

**Comment by NicolasT** [comment]
Hello! Indeed, the minion ID needs to be set properly in `bootstrap.yaml` and the `minion_id` file (if you create it manually), or match the discovered hostname (which will then be set in `minion_id` automatically if the file doesn't exist).

As to why `salt-api` wouldn't answer, can you check whether it's running in the first place (`ps afx` should show it), and/or check its logs (in `/var/log/containers/salt-master-NODENAME_kube-system_salt-api-UUID.log`, for some value of `NODENAME` and `UUID`).

**Comment by Abhishek627** [comment]
@NicolasT I think it was issue with firewall blocking salt port. It worked now. Thank you !

**Comment by Abhishek627** [comment]
Also 1 clarification, if I want to validate new iso generated, can I mount it and redeploy on an existing setup ? If yes, does any existing file/folder needs to be cleaned before re-deployment for a fair test.

**Comment by NicolasT** [comment]
> @NicolasT I think it was issue with firewall blocking salt port. It worked now. Thank you !

OK. Please note MetalK8s does not manage your host firewall (we may in some later version), and we kind-of expect no firewall to be in place. If there is one, indeed a bunch of ports need to be opened.

**Comment by NicolasT** [comment]
> Also 1 clarification, if I want to validate new iso generated, can I mount it and redeploy on an existing setup ? If yes, can any existing file/folder needs to be cleaned before redeployment for a fair test.

We're looking into using GitHub's _Discussions_ feature for questions like this, rather than _Issues_ (which should track bugs, implementation tasks,...). Would you mind posting your question at https://github.com/scality/metalk8s/discussions instead?

I'll close this issue assuming the initial issue (which would've been a good candidate for _Discussions_ as well, if we had that enabled at the time you submitted it, but indeed we did not :wink:) has been resolved.
