### ISSUE TITLE
Fix broken taints on second execution of bootstrap

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#730]
Observed traceback:

```
    bootstrap:           ID: Apply control-plane taints
    bootstrap:     Function: kubernetes.node_taints_present
    bootstrap:         Name: bootstrap
    bootstrap:       Result: False
    bootstrap:      Comment: An exception occurred in this state: Traceback (most recent call last):
    bootstrap:                 File "/usr/lib/python2.7/site-packages/salt/state.py", line 1913, in call
    bootstrap:                   **cdata['kwargs'])
    bootstrap:                 File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1898, in wrapper
    bootstrap:                   return f(*args, **kwargs)
    bootstrap:                 File "/var/cache/salt/minion/extmods/states/kubernetes.py", line 1134, in node_taints_present
    bootstrap:                   existing_taints = {t['key']: t for t in all_node_taints}
    bootstrap:               TypeError: 'NoneType' object is not iterable
    bootstrap:      Started: 20:08:42.526252
    bootstrap:     Duration: 118.131 ms
    bootstrap:      Changes:
```

**Comment by NicolasT** [comment]
Fixed by #734
