### ISSUE TITLE
Registry may try to bind on an unknown external IP address

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#798]
While using `make vagrantup`, I kept hitting this error:
```
    bootstrap: [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
    bootstrap:   File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    bootstrap:     **cdata['kwargs'])
    bootstrap:   File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    bootstrap:     return f(*args, **kwargs)
    bootstrap:   File "/var/cache/salt/minion/extmods/states/docker_registry.py", line 115, in image_managed
    bootstrap:     name, tls_verify=tls_verify)
    bootstrap:   File "/var/cache/salt/minion/extmods/modules/docker_registry.py", line 52, in get_image_manifest
    bootstrap:     out['stderr']))
    bootstrap: CommandExecutionError: Failure while retrieving image manifest: time="2019-03-19T18:38:17Z" level=fatal msg="pinging docker registry returned: Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused"
[...]
    bootstrap:           ID: Import etcd image
    bootstrap:     Function: docker_registry.image_managed
    bootstrap:         Name: localhost:5000/metalk8s-2.0/etcd:3.2.18
    bootstrap:       Result: False
    bootstrap:      Comment: An exception occurred in this state: Traceback (most recent call last):
    bootstrap:                 File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    bootstrap:                   **cdata['kwargs'])
    bootstrap:                 File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    bootstrap:                   return f(*args, **kwargs)
    bootstrap:                 File "/var/cache/salt/minion/extmods/states/docker_registry.py", line 115, in image_managed
    bootstrap:                   name, tls_verify=tls_verify)
    bootstrap:                 File "/var/cache/salt/minion/extmods/modules/docker_registry.py", line 52, in get_image_manifest
    bootstrap:                   out['stderr']))
    bootstrap:               CommandExecutionError: Failure while retrieving image manifest: time="2019-03-19T18:38:17Z" level=fatal msg="pinging docker registry returned: Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused"
    bootstrap:      Started: 18:38:17.750602
    bootstrap:     Duration: 58.176 ms
    bootstrap:      Changes:   
```

Symptom is: registry is not working. Container was in `Exited` state.

While looking at the logs of the container, I've seen:

```
time="2019-03-19T18:44:05.495623441Z" level=fatal msg="listen tcp 82.216.111.26:5000: bind: cannot assign requested address" 
```

Seems the `localhost` resolution may not work as expected.

**Comment by sayf-eddine-scality** [comment]
I got this error, SFR has an entry for localhost.... you just need to point your dns out of theirs, 8.8.8.8 or if you dont like google go 1.1.1.1

**Comment by charlesprost** [comment]
Won't be fixed, it's due to misconfiguration on the system.
