### ISSUE TITLE
Flakiness in CI during bootstrap run: calico-config ConfigMap

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#891]
The `metalk8s.orchestrate.bootstrap_with_master` sometime fails with:

```
-----------
                        ID: Deploy calico-config (ConfigMap)
                  Function: kubernetes.configmap_present
                      Name: calico-config
                    Result: False
                   Comment: An exception occurred in this state: Traceback (most recent call last):
                              File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
                                **cdata['kwargs'])
                              File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
                                return f(*args, **kwargs)
                              File "/var/cache/salt/minion/extmods/states/kubernetes.py", line 714, in configmap_present
                                'data': res['data']
                            TypeError: 'NoneType' object has no attribute '__getitem__'
                   Started: 17:28:09.053960
                  Duration: 4731.722 ms
                   Changes:
```

Investigation and reproducing instructions are needed.

**Comment by sayf-eddine-scality** [comment]
Although I dont see a reason for the data to be None but we can just use `.get` to not stop here because the result is already `True`

**Comment by sayf-eddine-scality** [comment]
Closing this as not seen recently and as it is not a problem from our side
