### ISSUE TITLE
Issue with custom kubernetes modules and states

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#991]
Since we "forked" the salt `kubernetes.py` modules and states and renamed to `kubernetesmod.py` when salt 2018 still use `kubernetes.py` as name we got some issue.

If we try to use a function that exist in salt internal kubernetes module we will use this one even if it's also define in our custom kubernetes module (just renaming the file to `kubernetes.py` fix the issue (but then we have some issue when we try to `import kubernetes` in our other custom salt modules))
```
[root@bootstrap ~]# salt-call kubernetes.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'host'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 213, in ping
    nodes(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 229, in nodes
    _setup_conn(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 147, in _setup_conn
    kubernetes.client.configuration.host != host or
AttributeError: 'module' object has no attribute 'host'
[root@bootstrap ~]# mv /srv/scality/metalk8s-2.0/salt/_modules/kubernetes{mod,}.py 
[root@bootstrap ~]# salt-call saltutil.sync_all saltenv=metalk8s-2.0
local:
    ----------
    beacons:
    clouds:
    engines:
    grains:
    log_handlers:
    modules:
        - modules.kubernetes
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    thorium:
    utils:
[root@bootstrap ~]# crictl exec -it 39827fa4aa8d7 salt '*' kubernetes.ping
bootstrap:
    False
```

If we try to call a function existing in both python file as our filename is `kubernetesmod.py` it's take the one from salt internal but if the function is only define in our custom module it's ok
```
[root@bootstrap ~]# tail -2 /srv/scality/metalk8s-2.0/salt/_modules/kubernetesmod.py 
def ping2(**kwargs):
    return ping(**kwargs)
[root@bootstrap ~]# salt-call saltutil.sync_all saltenv=metalk8s-2.0
local:
    ----------
    beacons:
    clouds:
    engines:
    grains:
    log_handlers:
    modules:
        - modules.kubernetesmod
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    thorium:
    utils:
[root@bootstrap ~]# salt-call kubernetes.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'host'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 213, in ping
    nodes(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 229, in nodes
    _setup_conn(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 147, in _setup_conn
    kubernetes.client.configuration.host != host or
AttributeError: 'module' object has no attribute 'host'
[root@bootstrap ~]# salt-call kubernetes.ping2
local:
    False
```

Suggested changes:
- Rename our custom salt modules and states to `metalk8s_kubernetes.py`
- changes each and every call to kubernetes states or module to `metalk8s_kubernetes` in our state file (.sls) and also in every call in our custom kubernetes states  `_states/metalk8s_kubernetes.py`

**Comment by TeddyAndrieux** [comment]
FY: https://github.com/saltstack/salt/issues/52521
